Clinica/Models/estado_cita.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_cita
    {
        public estado_cita()
        {
            this.cita = new HashSet<cita>();
        }
    
        public int id_estado_cita { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
    }
}

Clinica/Controllers/estado_citaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica.Models;

namespace Clinica.Controllers
{
    public class estado_citaController : Controller
    {
        private ClinicaDBEntities db = new ClinicaDBEntities();

        // GET: estado_cita
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            return View(db.estado_cita.ToList());
        }

        // GET: estado_cita/Details/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            estado_cita estado_cita = db.estado_cita.Find(id);
            if (estado_cita == null)
            {
                return HttpNotFound();
            }
            return View(estado_cita);
        }

        // GET: estado_cita/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: estado_cita/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_estado_cita,estado")] estado_cita estado_cita)
        {
            if (ModelState.IsValid)
            {
                db.estado_cita.Add(estado_cita);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estado_cita);
        }

        // GET: estado_cita/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            estado_cita estado_cita = db.estado_cita.Find(id);
            if (estado_cita == null)
            {
                return HttpNotFound();
            }
            return View(estado_cita);
        }

        // POST: estado_cita/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_estado_cita,estado")] estado_cita estado_cita)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estado_cita).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estado_cita);
        }

        // GET: estado_cita/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            estado_cita estado_cita = db.estado_cita.Find(id);
            if (estado_cita == null)
            {
                return HttpNotFound();
            }
            return View(estado_cita);
        }

        // POST: estado_cita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            estado_cita estado_cita = db.estado_cita.Find(id);
            db.estado_cita.Remove(estado_cita);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinica/Views/estado_cita/Create.cshtml
@model Clinica.Models.estado_cita

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>estado_cita</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica/Views/estado_cita/Delete.cshtml
@model Clinica.Models.estado_cita

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>estado_cita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Clinica/Views/estado_cita/Details.cshtml
@model Clinica.Models.estado_cita

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>estado_cita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_estado_cita }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Clinica/Views/estado_cita/Edit.cshtml
@model Clinica.Models.estado_cita

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>estado_cita</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_estado_cita)

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica/Views/estado_cita/Index.cshtml
@model IEnumerable<Clinica.Models.estado_cita>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@section head_table{
    <div class="row">
        <div class="col-lg-12 text-right">
            <button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("Create", "estado_cita")'"><i class="fa fa-plus"></i> Contacto</button>
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.estado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.estado)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_estado_cita }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_estado_cita }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_estado_cita })
        </td>
    </tr>
}

</table>