Clinica/Controllers/medicamentoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica.Models;
using System.IO;

namespace Clinica.Controllers
{
    public class medicamentoesController : Controller
    {
        private ClinicaDBEntities db = new ClinicaDBEntities();

        // GET: medicamentoes
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            return View(db.medicamento.ToList());
        }

        // GET: medicamentoes/Details/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicamento medicamento = db.medicamento.Find(id);
            if (medicamento == null)
            {
                return HttpNotFound();
            }
            return View(medicamento);
        }

        // GET: medicamentoes/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: medicamentoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_medicamento,nombre,precio,imagen")] medicamento medicamento, HttpPostedFileBase ImageFile)
        {
            string filename = "";
            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                // extract only the fielname
                filename = Path.GetFileName(ImageFile.FileName);
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/uploads"), filename);
                ImageFile.SaveAs(path);
            }
            else
            {
                filename = "default-product-image.jpg";
            }
            medicamento.imagen = filename;
            if (ModelState.IsValid)
            {
                db.medicamento.Add(medicamento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicamento);
        }

        // GET: medicamentoes/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicamento medicamento = db.medicamento.Find(id);
            if (medicamento == null)
            {
                return HttpNotFound();
            }
            return View(medicamento);
        }

        // POST: medicamentoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_medicamento,nombre,precio,imagen")] medicamento medicamento, HttpPostedFileBase ImageFile)
        {
            string filename = "";
            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                // extract only the fielname
                filename = Path.GetFileName(ImageFile.FileName);
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/uploads"), filename);
                ImageFile.SaveAs(path);
            }
            else
            {
                filename = "default-product-image.jpg";
            }
            medicamento.imagen = filename;
            if (ModelState.IsValid)
            {
                db.Entry(medicamento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicamento);
        }

        // GET: medicamentoes/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicamento medicamento = db.medicamento.Find(id);
            if (medicamento == null)
            {
                return HttpNotFound();
            }
            return View(medicamento);
        }

        // POST: medicamentoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            medicamento medicamento = db.medicamento.Find(id);
            db.medicamento.Remove(medicamento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinica/Views/medicamentoes/Create.cshtml
@model Clinica.Models.medicamento

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "medicamentoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>medicamento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })*@
                <input type="file" id="ImageFile" name="ImageFile" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            validateFloatPositive('precio');
        });
    </script>
}

Clinica/Views/medicamentoes/Delete.cshtml
@model Clinica.Models.medicamento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>medicamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @{
                string dir_img = "";
                if (Model.imagen == "default-product-image.jpg")
                {
                    dir_img = "images";
                }
                else
                {
                    dir_img = "uploads";
                }
            }
            <img src="~/@dir_img/@Html.DisplayFor(model => model.imagen)" class="img-responsive" />
            @*<img src="~/images/@Html.DisplayFor(model => model.imagen)" class="img-responsive" />*@
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Clinica/Views/medicamentoes/Details.cshtml
@model Clinica.Models.medicamento

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>medicamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @{
                string dir_img = "";
                if (Model.imagen == "default-product-image.jpg")
                {
                    dir_img = "images";
                }
                else
                {
                    dir_img = "uploads";
                }
            }
            <img src="~/@dir_img/@Html.DisplayFor(model => model.imagen)" class="img-responsive" />
            @*<img src="~/images/@Html.DisplayFor(model => model.imagen)" class="img-responsive"/>*@
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_medicamento }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Clinica/Views/medicamentoes/Edit.cshtml
@model Clinica.Models.medicamento

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "medicamentoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>medicamento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_medicamento)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" id="ImageFile" name="ImageFile" />
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @{
    string dir_img = "";
    if (Model.imagen == "default-product-image.jpg")
    {
        dir_img = "images";
    }
    else
    {
        dir_img = "uploads";
    }
                }
                <img src="~/@dir_img/@Html.DisplayFor(model => model.imagen)" class="img-responsive" />
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica/Views/medicamentoes/Index.cshtml
@model IEnumerable<Clinica.Models.medicamento>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_table.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imagen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.precio)
        </td>
        <td>
            @{
                string dir_img = "";
                if (item.imagen == "default-product-image.jpg")
                {
                    dir_img = "images";
                }
                else
                {
                    dir_img = "uploads";
                }
            }
            <img src="~/@dir_img/@Html.DisplayFor(modelItem => item.imagen)" class="img-responsive" width="150"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_medicamento }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_medicamento }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_medicamento })
        </td>
    </tr>
}

</table>