Clinica/Models/ofertas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofertas
    {
        public int id_ofertas { get; set; }
        public Nullable<int> id_medicamentos { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    
        public virtual medicamento medicamento { get; set; }
    }
}

Clinica/Controllers/ofertasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica.Models;

namespace Clinica.Controllers
{
    public class ofertasController : Controller
    {
        private ClinicaDBEntities db = new ClinicaDBEntities();

        // GET: ofertas
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {

            var ofertas = db.ofertas.Include(o => o.medicamento);
            return View(ofertas.ToList());
        }

        // GET: ofertas/Details/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ofertas ofertas = db.ofertas.Find(id);
            if (ofertas == null)
            {
                return HttpNotFound();
            }
            return View(ofertas);
        }

        // GET: ofertas/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            ViewBag.id_medicamentos = new SelectList(db.medicamento, "id_medicamento", "nombre");
            return View();
        }

        // POST: ofertas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_ofertas,id_medicamentos,descuento,fecha_inicio,fecha_fin")] ofertas ofertas)
        {
            if (ModelState.IsValid)
            {
                db.ofertas.Add(ofertas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_medicamentos = new SelectList(db.medicamento, "id_medicamento", "nombre", ofertas.id_medicamentos);
            return View(ofertas);
        }

        // GET: ofertas/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ofertas ofertas = db.ofertas.Find(id);
            if (ofertas == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_medicamentos = new SelectList(db.medicamento, "id_medicamento", "nombre", ofertas.id_medicamentos);
            return View(ofertas);
        }

        // POST: ofertas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_ofertas,id_medicamentos,descuento,fecha_inicio,fecha_fin")] ofertas ofertas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ofertas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_medicamentos = new SelectList(db.medicamento, "id_medicamento", "nombre", ofertas.id_medicamentos);
            return View(ofertas);
        }

        // GET: ofertas/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ofertas ofertas = db.ofertas.Find(id);
            if (ofertas == null)
            {
                return HttpNotFound();
            }
            return View(ofertas);
        }

        // POST: ofertas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ofertas ofertas = db.ofertas.Find(id);
            db.ofertas.Remove(ofertas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult OfertasCliente() 
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinica/Views/ofertas/Delete.cshtml
@model Clinica.Models.ofertas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ofertas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descuento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descuento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_inicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_inicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_fin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_fin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.medicamento.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medicamento.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Clinica/Views/ofertas/Details.cshtml
@model Clinica.Models.ofertas

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>ofertas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descuento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descuento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_inicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_inicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_fin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_fin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.medicamento.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medicamento.nombre)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Index", "ofertas")'">
        <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Regresar inicio
    </button>&nbsp;
    <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="location.href='@Url.Action("Edit", "usuarios", new { id = Model.id_ofertas })'">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> &nbsp; Editar
    </button>
</p>

Clinica/Views/ofertas/Edit.cshtml
@model Clinica.Models.ofertas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>ofertas</h4>
                <hr />
                <div class="row">
                    <div class="col-lg-7 col-lg-offset-2">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id_ofertas)

                        <div class="form-group">
                            @Html.LabelFor(model => model.id_medicamentos, "id_medicamentos", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("id_medicamentos", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.id_medicamentos, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.descuento, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.descuento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.descuento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha_inicio, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.fecha_inicio, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.fecha_inicio, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha_fin, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.fecha_fin, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.fecha_fin, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12 col-md-12 col-lg-12 text-right">
                                <input type="submit" value="Guardar" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div>
    <button type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Index", "ofertas")'">
        <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Regresar inicio
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica/Views/ofertas/Index.cshtml
@model IEnumerable<Clinica.Models.ofertas>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@section head_table{
    <div class="row">
        <div class="col-lg-12 text-right">
            <button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("Create", "ofertas")'"><i class="fa fa-plus"></i> Oferta</button>
        </div>
    </div>
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table id="grid" class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.descuento)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fecha_inicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fecha_fin)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.medicamento.nombre)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.descuento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fecha_inicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fecha_fin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.medicamento.nombre)
                        </td>
                        <td>
                            <button title="Detalles" type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Details", "ofertas", new { id = item.id_ofertas })'">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Detalle
                            </button>
                            &nbsp;
                            <button type="button" title="Editar" class="btn btn-primary" aria-label="Left Align" onclick="location.href='@Url.Action("Edit", "ofertas", new { id = item.id_ofertas })'">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
                            </button>
                            &nbsp;
                            <button type="button" title="Eliminar" class="btn btn-danger" aria-label="Left Align" onclick="location.href='@Url.Action("Delete", "ofertas", new { id = item.id_ofertas })'">
                                <i class="fa fa-times" aria-hidden="true"></i> Elminar
                            </button>
                            
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#grid').DataTable();
        });
    </script>
}

Clinica/Views/ofertas/OfertasCliente.cshtml
@model IEnumerable<Clinica.Models.ofertas>

@{
    ViewBag.Title = "OfertasCliente";
    Layout = "~/Views/Shared/_Layout_user.cshtml";
}

<h2>OfertasCliente</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.descuento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_inicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_fin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.medicamento.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.descuento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_inicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_fin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.medicamento.nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_ofertas }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_ofertas }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_ofertas })
        </td>
    </tr>
}

</table>