Clinica/Models/usuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.cita = new HashSet<cita>();
            this.cita1 = new HashSet<cita>();
            this.receta = new HashSet<receta>();
            this.receta1 = new HashSet<receta>();
            this.cotizacion = new HashSet<cotizacion>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public int edad { get; set; }
        public string password { get; set; }
        public int id_tipo_usuario { get; set; }
        public string id_usuaro_asp { get; set; }
        public string id_rol_asp { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
        public virtual ICollection<cita> cita1 { get; set; }
        public virtual ICollection<receta> receta { get; set; }
        public virtual ICollection<receta> receta1 { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
        public virtual ICollection<cotizacion> cotizacion { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}

Clinica/Controllers/usuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica.Models;

namespace Clinica.Controllers
{
    public class usuariosController : Controller
    {
        private ClinicaDBEntities db = new ClinicaDBEntities();
        private ApplicationDbContext dc = new ApplicationDbContext();

        // GET: usuarios
        [Authorize(Roles = "Administrador")] 
        public ActionResult Index()
        {
            var usuario = db.usuario.Include(u => u.tipo_usuario);
            return View(usuario.ToList());
        }

        // GET: usuarios/Details/5
        [Authorize(Roles = "Administrador")] 
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: usuarios/Create
        [Authorize(Roles = "Administrador")] 
        public ActionResult Create()
        {
            ViewBag.id_tipo_usuario = new SelectList(db.tipo_usuario, "id_tipo_usuario", "tipo_usuario1");
            return View();
        }

        // POST: usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_usuario,nombre,apellido,correo,telefono,direccion,edad,password,id_tipo_usuario")] usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_tipo_usuario = new SelectList(db.tipo_usuario, "id_tipo_usuario", "tipo_usuario1", usuario.id_tipo_usuario);
            return View(usuario);
        }

        // GET: usuarios/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_tipo_usuario = new SelectList(db.tipo_usuario, "id_tipo_usuario", "tipo_usuario1", usuario.id_tipo_usuario);
            return View(usuario);
        }

        // POST: usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_usuario,nombre,apellido,correo,telefono,direccion,edad,password,id_tipo_usuario")] usuario usuario)
        {
            if (ModelState.IsValid)
            {       
                
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_tipo_usuario = new SelectList(db.tipo_usuario, "id_tipo_usuario", "tipo_usuario1", usuario.id_tipo_usuario);
            return View(usuario);
        }

        // GET: usuarios/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            usuario usuario = db.usuario.Find(id);
            db.usuario.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        public ActionResult RedirectManage(string id)
        {
            return RedirectToAction("AdminRolesUsers", "Manage", id);
        }
    }
}

Clinica/Views/usuarios/Create.cshtml
@model Clinica.Models.usuario

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Crear Usuario</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-7 col-lg-offset-2">
            <hr />
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.edad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.id_tipo_usuario, "id_tipo_usuario", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("id_tipo_usuario", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.id_tipo_usuario, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                </div>

            </div>

        </div>
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="row">
                <div class="col-sm-1 col-md-1 col-lg-1">
                    <button type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Index", "usuarios")'">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Regresar inicio
                    </button>
                </div>
                <div class="col-sm-1 col-md-2 col-lg-2 col-sm-2 col-md-2 col-sm-offset-7 col-lg-offset-6 col-md-offset-6 text-right">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            </div>
            
            
        </div>

    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica/Views/usuarios/Delete.cshtml
@model Clinica.Models.usuario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_usuario.tipo_usuario1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_usuario.tipo_usuario1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Clinica/Views/usuarios/Details.cshtml
@model Clinica.Models.usuario

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_usuario.tipo_usuario1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_usuario.tipo_usuario1)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Index", "usuarios")'">
        <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Regresar inicio
    </button>&nbsp;
    <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="location.href='@Url.Action("Edit", "usuarios", new { id = Model.id_usuario })'">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> &nbsp; Editar
    </button>
</p>

Clinica/Views/usuarios/Edit.cshtml
@model Clinica.Models.usuario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>usuario</h4>
                <hr />
                <div class="row">
                    <div class="col-lg-7 col-lg-offset-2">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id_usuario)

                        <div class="form-group">
                            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.edad, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.id_tipo_usuario, "id_tipo_usuario", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("id_tipo_usuario", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.id_tipo_usuario, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12 col-md-12 col-lg-12 text-right">
                                <input type="submit" value="Guardar" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div>
            <button type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Index", "usuarios")'">
                <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp; Regresar inicio
            </button>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica/Views/usuarios/Index.cshtml
@model IEnumerable<Clinica.Models.usuario>

@{
    ViewBag.Title = "Index";
}
<h2>Usuarios</h2>

@section head_table{
    <div class="row">
        <div class="col-lg-12 text-right">
            <button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("Create", "usuarios")'"><i class="fa fa-plus"></i> Contacto</button>
        </div>
    </div>
}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table id="grid" class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.apellido)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.correo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.telefono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.direccion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.edad)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.password)
                    </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.tipo_usuario.tipo_usuario1)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.correo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.direccion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.edad)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.password)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelitem => item.tipo_usuario.tipo_usuario1)<br />
                            
                            @*<a href="@Url.Action("AdminRolesUsers", "Manage", new { id = item.id_usuario })">Editar rol</a>*@
                            @*@Html.ActionLink("Editar Rol", "AdminRolesUsers", "Manage", new { id = item.id_rol_asp })*@
                        </td>
                        <td>
                            <button title ="Detalles" type="button" class="btn btn-default" aria-label="Left Align" onclick="location.href='@Url.Action("Details", "usuarios", new { id = item.id_usuario })'">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i> Detalle
                            </button>
                            &nbsp;
                            <button type="button" title="Editar" class="btn btn-primary" aria-label="Left Align" onclick="location.href='@Url.Action("Edit", "usuarios", new { id=item.id_usuario})'">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
                            </button>
                            &nbsp;
                            <button type="button" title="Eliminar" class="btn btn-danger" aria-label="Left Align" onclick="location.href='@Url.Action("Delete", "usuarios", new { id = item.id_usuario })'">
                                <i class="fa fa-times" aria-hidden="true"></i> Elminar
                            </button>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#grid').DataTable();
        });
    </script>
}